language: node_js
node_js:
 — "7"
script:
 — echo "Deploy!!"
install:
 — npm install -g firebase-tools
 - firebase init
after_success:
 — firebase deploy — project rainbowtables-dfc4f — token $FIREBASE_TOKEN
